// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "updateAuthors": boolean;
      "upgradePreprints": boolean;
      "skipChinese": boolean;
      "backupToExtra": boolean;
      "fillEmptyOnly": boolean;
      "recurseCollections": boolean;
      "titleSimilarityThreshold": string;
      "delayMs": string;
      "maxItems": string;
      "concurrency": string;
      "useCrossref": boolean;
      "useOpenAlex": boolean;
      "useS2": boolean;
      "useDBLP": boolean;
      "contactEmail": string;
      "s2ApiKey": string;
      "fieldTitle": boolean;
      "fieldPublicationTitle": boolean;
      "fieldDate": boolean;
      "fieldVolume": boolean;
      "fieldIssue": boolean;
      "fieldPages": boolean;
      "fieldDOI": boolean;
      "fieldAbstractNote": boolean;
      "fieldConferenceName": boolean;
      "fieldProceedingsTitle": boolean;
    };
  }
}
